pool:
  vmImage: ubuntu-latest

trigger:
- azure-setup

steps:
- script: | 
    echo Hello, world!
    ls
    chmod +x execute.sh
    source execute.sh
    ./execute.sh build
  displayName: 'Build Environment'