pool:
  vmImage: ubuntu-latest

trigger:
- azure-setup

steps:
- script: |
    echo "Build Environment"
    chmod +x environment.sh && source environment.sh && ./environment.sh
    echo $DOCKERFILE
    #./execute.sh build
  displayName: 'Build Environment'