pool:
  vmImage: ubuntu-latest

trigger:
- azure-setup

steps:
- script: |
    echo "Build Environment"
    ./execute.sh build
    ./execute.sh run
  displayName: 'Build Environment'

- script: |
    echo "Cleaning cache and build"
    ./execute.sh command clean
  displayName: 'Pre-setup'

- script: |
    echo "Running Tests"
    ./execute.sh command test
  displayName: 'Run Tests'


- script: |
    echo "Build Source Code as Release"
    ./execute.sh command assembleRelease
  displayName: 'Build Source Code'


- script: |
    echo "Extract Build"
    ./execute.sh extract
  displayName: 'Extract Build'


- script: |
    echo "Removing used resources"
    ./execute.sh remove
  displayName: 'Cleanup'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.apk'
    TargetFolder: '$(build.artifactstagingdirectory)'
  displayName: 'Copy File to : $(build.artifactstagingdirectory)'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  displayName: 'Publish to Artifact'